# Generated by Django 3.2.10 on 2021-12-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20211216_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='yarn',
            name='tags',
            field=models.ManyToManyField(blank=True, to='shop.Tag'),
        ),
    ]
