# Generated by Django 3.2.10 on 2021-12-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20211216_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarn',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
