# Generated by Django 3.2.10 on 2021-12-17 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='yarn',
        ),
    ]
