# Generated by Django 3.2.10 on 2021-12-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_post_comment_yarn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='contact',
            field=models.CharField(max_length=20),
        ),
    ]
